// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Header";
import Footer from "./components/footer";  


const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "E Digital India - Professional Certification Courses",

  description: "Transform your career with industry-leading certification courses in SAP, Digital Marketing, Web Development, Data Science, Android Development, and Soft Skills.",
  keywords: "SAP certification, digital marketing course, web development, data science course, Android development, soft skills training",
  authors: [{ name: "E Digital India" }],
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: "https://edigitalindia.com",
    siteName: "E Digital India",
    title: "E Digital India - Professional Certification Courses",
    description: "Transform your career with industry-leading certification courses",
  },
  robots: {
    index: true,
    follow: true,
  },
   icons: {
    icon: "/logo.png", // Simple single icon
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         {/* <link rel="icon" href="/logo.png" type="image/png" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${inter.variable} font-sans antialiased`}>
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow">
            {children}
          </main>
          
              <Footer/>

          {/* <footer className="bg-gray-900 text-white py-8">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center">
                <p className="text-gray-400">
                  © {new Date().getFullYear()} E Digital India. All rights reserved.
                </p>
                <p className="text-gray-500 text-sm mt-2">
                  Jamshedpur, Jharkhand | Contact: +91 XXXXX XXXXX
                </p>
              </div>
            </div>
          </footer> */}
        </div>
      </body>
    </html>
  );
}